const List<({String fileName, String content})> blocRuleFiles = [
  (fileName: 'blocs_no_direct_data_access_arch_test.dart', content: _blocNoDirectDataAccess),
  (fileName: 'cubits_no_direct_data_access_arch_test.dart', content: _cubitNoDirectDataAccess),
  (fileName: 'repositories_in_data_layer_arch_test.dart', content: _repositoriesInDataLayer),
  (fileName: 'datasources_in_data_layer_arch_test.dart', content: _dataSourcesInDataLayer),
  (fileName: 'use_cases_in_domain_layer_arch_test.dart', content: _useCasesInDomainLayer),
  (fileName: 'domain_no_presentation_dependency_arch_test.dart', content: _domainNoPresentationDependency),
];

const String _blocNoDirectDataAccess = r'''
import 'package:dartunit/dartunit.dart';

/// BLoC Architecture — generated by dartunit init --template bloc
///
/// Rule: BLoC classes must not access the data layer directly.
/// All data access must go through the domain/repository layer.
void main(List<String> args) => archTest(
      args,
      ArchitectureRule(
        description: 'BLoC classes must not access the data layer directly',
        severity: RuleSeverity.error,
        selector: ClassSelector(namePattern: r'.*Bloc$'),
        predicate: NotPredicate(DependOnFolderPredicate('lib/data')),
      ),
    );
''';

const String _cubitNoDirectDataAccess = r'''
import 'package:dartunit/dartunit.dart';

/// BLoC Architecture — generated by dartunit init --template bloc
///
/// Rule: Cubit classes must not access the data layer directly.
/// All data access must go through the domain/repository layer.
void main(List<String> args) => archTest(
      args,
      ArchitectureRule(
        description: 'Cubit classes must not access the data layer directly',
        severity: RuleSeverity.error,
        selector: ClassSelector(namePattern: r'.*Cubit$'),
        predicate: NotPredicate(DependOnFolderPredicate('lib/data')),
      ),
    );
''';

const String _repositoriesInDataLayer = r'''
import 'package:dartunit/dartunit.dart';

/// BLoC Architecture — generated by dartunit init --template bloc
///
/// Rule: Repository implementations must reside in lib/data.
/// Interfaces (contracts) live in lib/domain; impls live in lib/data.
void main(List<String> args) => archTest(
      args,
      ArchitectureRule(
        description: 'Repository implementations must reside in lib/data',
        severity: RuleSeverity.error,
        selector: ClassSelector(namePattern: r'.*RepositoryImpl$'),
        predicate: DependOnFolderPredicate('lib/data'),
      ),
    );
''';

const String _dataSourcesInDataLayer = r'''
import 'package:dartunit/dartunit.dart';

/// BLoC Architecture — generated by dartunit init --template bloc
///
/// Rule: Data source classes must reside in lib/data.
/// Data sources are the lowest-level data access objects.
void main(List<String> args) => archTest(
      args,
      ArchitectureRule(
        description: 'Data source classes must reside in lib/data',
        severity: RuleSeverity.error,
        selector: ClassSelector(namePattern: r'.*DataSource$'),
        predicate: DependOnFolderPredicate('lib/data'),
      ),
    );
''';

const String _useCasesInDomainLayer = r'''
import 'package:dartunit/dartunit.dart';

/// BLoC Architecture — generated by dartunit init --template bloc
///
/// Rule: Use case classes must reside in lib/domain.
/// Use cases encapsulate business logic and must stay in the domain layer.
void main(List<String> args) => archTest(
      args,
      ArchitectureRule(
        description: 'Use case classes must reside in lib/domain',
        severity: RuleSeverity.error,
        selector: ClassSelector(namePattern: r'.*UseCase$'),
        predicate: DependOnFolderPredicate('lib/domain'),
      ),
    );
''';

const String _domainNoPresentationDependency = r'''
import 'package:dartunit/dartunit.dart';

/// BLoC Architecture — generated by dartunit init --template bloc
///
/// Rule: Domain layer must not depend on the presentation or BLoC layer.
/// The domain is framework-agnostic and must not know about UI concerns.
void main(List<String> args) => archTest(
      args,
      ArchitectureRule(
        description: 'Domain layer must not depend on presentation or BLoC layer',
        severity: RuleSeverity.error,
        selector: ClassSelector(folder: 'lib/domain'),
        predicate: AndPredicate([
          NotPredicate(DependOnFolderPredicate('lib/presentation')),
          NotPredicate(DependOnFolderPredicate('lib/blocs')),
        ]),
      ),
    );
''';
