const List<({String fileName, String content})> cleanRuleFiles = [
  (fileName: 'domain_no_data_dependency_arch_test.dart', content: _domainNoDataDependency),
  (fileName: 'domain_no_presentation_dependency_arch_test.dart', content: _domainNoPresentationDependency),
  (fileName: 'presentation_no_data_dependency_arch_test.dart', content: _presentationNoDataDependency),
  (fileName: 'repositories_in_data_layer_arch_test.dart', content: _repositoriesInDataLayer),
  (fileName: 'use_cases_in_domain_layer_arch_test.dart', content: _useCasesInDomainLayer),
  (fileName: 'entities_in_domain_layer_arch_test.dart', content: _entitiesInDomainLayer),
];

const String _domainNoDataDependency = r'''
// Clean Architecture — generated by dartunit init --template clean
//
// Rule: Domain layer must not depend on the data layer.
// Domain defines the contracts; data implements them.

import 'package:dartunit/dartunit.dart';

void main(List<String> args) => archTest(
      args,
      ArchitectureRule(
        description: 'Domain layer must not depend on the data layer',
        severity: RuleSeverity.error,
        selector: ClassSelector(folder: 'lib/domain'),
        predicate: NotPredicate(DependOnFolderPredicate('lib/data')),
      ),
    );
''';

const String _domainNoPresentationDependency = r'''
// Clean Architecture — generated by dartunit init --template clean
//
// Rule: Domain layer must not depend on the presentation layer.
// The domain is the innermost layer and must remain framework-agnostic.

import 'package:dartunit/dartunit.dart';

void main(List<String> args) => archTest(
      args,
      ArchitectureRule(
        description: 'Domain layer must not depend on the presentation layer',
        severity: RuleSeverity.error,
        selector: ClassSelector(folder: 'lib/domain'),
        predicate: NotPredicate(DependOnFolderPredicate('lib/presentation')),
      ),
    );
''';

const String _presentationNoDataDependency = r'''
// Clean Architecture — generated by dartunit init --template clean
//
// Rule: Presentation layer must not access the data layer directly.
// All data access must go through domain use cases.

import 'package:dartunit/dartunit.dart';

void main(List<String> args) => archTest(
      args,
      ArchitectureRule(
        description: 'Presentation layer must not access the data layer directly',
        severity: RuleSeverity.error,
        selector: ClassSelector(folder: 'lib/presentation'),
        predicate: NotPredicate(DependOnFolderPredicate('lib/data')),
      ),
    );
''';

const String _repositoriesInDataLayer = r'''
// Clean Architecture — generated by dartunit init --template clean
//
// Rule: Repository implementations must reside in lib/data.
// Interfaces live in lib/domain; implementations live in lib/data.

import 'package:dartunit/dartunit.dart';

void main(List<String> args) => archTest(
      args,
      ArchitectureRule(
        description: 'Repository implementations must reside in lib/data',
        severity: RuleSeverity.error,
        selector: ClassSelector(namePattern: r'.*RepositoryImpl$'),
        predicate: DependOnFolderPredicate('lib/data'),
      ),
    );
''';

const String _useCasesInDomainLayer = r'''
// Clean Architecture — generated by dartunit init --template clean
//
// Rule: Use case classes must reside in lib/domain.
// Use cases encapsulate business logic and must stay in the domain layer.

import 'package:dartunit/dartunit.dart';

void main(List<String> args) => archTest(
      args,
      ArchitectureRule(
        description: 'Use case classes must reside in lib/domain',
        severity: RuleSeverity.error,
        selector: ClassSelector(namePattern: r'.*UseCase$'),
        predicate: DependOnFolderPredicate('lib/domain'),
      ),
    );
''';

const String _entitiesInDomainLayer = r'''
// Clean Architecture — generated by dartunit init --template clean
//
// Rule: Entity classes must reside in lib/domain.
// Entities are the core business objects and belong to the domain layer.

import 'package:dartunit/dartunit.dart';

void main(List<String> args) => archTest(
      args,
      ArchitectureRule(
        description: 'Entity classes must reside in lib/domain',
        severity: RuleSeverity.error,
        selector: ClassSelector(namePattern: r'.*Entity$'),
        predicate: DependOnFolderPredicate('lib/domain'),
      ),
    );
''';
