const List<({String fileName, String content})> mvcRuleFiles = [
  (fileName: 'models_no_controller_dependency_arch_test.dart', content: _modelsNoControllerDependency),
  (fileName: 'models_no_view_dependency_arch_test.dart', content: _modelsNoViewDependency),
  (fileName: 'controllers_in_controllers_folder_arch_test.dart', content: _controllersInControllersFolder),
  (fileName: 'views_no_data_dependency_arch_test.dart', content: _viewsNoDataDependency),
  (fileName: 'services_in_services_folder_arch_test.dart', content: _servicesInServicesFolder),
];

const String _modelsNoControllerDependency = r'''
// MVC Architecture — generated by dartunit init --template mvc
//
// Rule: Models must not depend on controllers.
// Models represent pure data and business logic, free of controller concerns.

import 'package:dartunit/dartunit.dart';

void main(List<String> args) => archTest(
      args,
      ArchitectureRule(
        description: 'Models must not depend on controllers',
        severity: RuleSeverity.error,
        selector: ClassSelector(folder: 'lib/models'),
        predicate: NotPredicate(DependOnFolderPredicate('lib/controllers')),
      ),
    );
''';

const String _modelsNoViewDependency = r'''
// MVC Architecture — generated by dartunit init --template mvc
//
// Rule: Models must not depend on views.
// Models must remain independent of any UI layer.

import 'package:dartunit/dartunit.dart';

void main(List<String> args) => archTest(
      args,
      ArchitectureRule(
        description: 'Models must not depend on views',
        severity: RuleSeverity.error,
        selector: ClassSelector(folder: 'lib/models'),
        predicate: NotPredicate(DependOnFolderPredicate('lib/views')),
      ),
    );
''';

const String _controllersInControllersFolder = r'''
// MVC Architecture — generated by dartunit init --template mvc
//
// Rule: Controller classes must reside in lib/controllers.

import 'package:dartunit/dartunit.dart';

void main(List<String> args) => archTest(
      args,
      ArchitectureRule(
        description: 'Controller classes must reside in lib/controllers',
        severity: RuleSeverity.warning,
        selector: ClassSelector(namePattern: r'.*Controller$'),
        predicate: DependOnFolderPredicate('lib/controllers'),
      ),
    );
''';

const String _viewsNoDataDependency = r'''
// MVC Architecture — generated by dartunit init --template mvc
//
// Rule: Views must not access models directly.
// Views must only interact with controllers.

import 'package:dartunit/dartunit.dart';

void main(List<String> args) => archTest(
      args,
      ArchitectureRule(
        description: 'Views must not access models directly',
        severity: RuleSeverity.error,
        selector: ClassSelector(folder: 'lib/views'),
        predicate: NotPredicate(DependOnFolderPredicate('lib/models')),
      ),
    );
''';

const String _servicesInServicesFolder = r'''
// MVC Architecture — generated by dartunit init --template mvc
//
// Rule: Service classes must reside in lib/services.
// Services encapsulate shared business logic used by controllers.

import 'package:dartunit/dartunit.dart';

void main(List<String> args) => archTest(
      args,
      ArchitectureRule(
        description: 'Service classes must reside in lib/services',
        severity: RuleSeverity.warning,
        selector: ClassSelector(namePattern: r'.*Service$'),
        predicate: DependOnFolderPredicate('lib/services'),
      ),
    );
''';
