const List<({String fileName, String content})> mvvmRuleFiles = [
  (fileName: 'viewmodels_no_view_dependency_arch_test.dart', content: _viewModelsNoViewDependency),
  (fileName: 'viewmodels_in_viewmodels_folder_arch_test.dart', content: _viewModelsInFolder),
  (fileName: 'views_no_data_dependency_arch_test.dart', content: _viewsNoDataDependency),
  (fileName: 'views_no_model_dependency_arch_test.dart', content: _viewsNoModelDependency),
  (fileName: 'models_no_viewmodel_dependency_arch_test.dart', content: _modelsNoViewModelDependency),
  (fileName: 'services_no_view_dependency_arch_test.dart', content: _servicesNoViewDependency),
];

const String _viewModelsNoViewDependency = r'''
// MVVM Architecture — generated by dartunit init --template mvvm
//
// Rule: ViewModels must not depend on views.
// ViewModels expose state and handle logic; they must remain view-agnostic.

import 'package:dartunit/dartunit.dart';

void main(List<String> args) => archTest(
      args,
      ArchitectureRule(
        description: 'ViewModels must not depend on views',
        severity: RuleSeverity.error,
        selector: ClassSelector(namePattern: r'.*ViewModel$'),
        predicate: NotPredicate(DependOnFolderPredicate('lib/views')),
      ),
    );
''';

const String _viewModelsInFolder = r'''
// MVVM Architecture — generated by dartunit init --template mvvm
//
// Rule: ViewModel classes must reside in lib/viewmodels.

import 'package:dartunit/dartunit.dart';

void main(List<String> args) => archTest(
      args,
      ArchitectureRule(
        description: 'ViewModel classes must reside in lib/viewmodels',
        severity: RuleSeverity.warning,
        selector: ClassSelector(namePattern: r'.*ViewModel$'),
        predicate: DependOnFolderPredicate('lib/viewmodels'),
      ),
    );
''';

const String _viewsNoDataDependency = r'''
// MVVM Architecture — generated by dartunit init --template mvvm
//
// Rule: Views must not access the data layer directly.
// Views must bind to ViewModels only.

import 'package:dartunit/dartunit.dart';

void main(List<String> args) => archTest(
      args,
      ArchitectureRule(
        description: 'Views must not access the data layer directly',
        severity: RuleSeverity.error,
        selector: ClassSelector(folder: 'lib/views'),
        predicate: NotPredicate(DependOnFolderPredicate('lib/data')),
      ),
    );
''';

const String _viewsNoModelDependency = r'''
// MVVM Architecture — generated by dartunit init --template mvvm
//
// Rule: Views must not access models directly.
// Views must only interact with ViewModels.

import 'package:dartunit/dartunit.dart';

void main(List<String> args) => archTest(
      args,
      ArchitectureRule(
        description: 'Views must not access models directly',
        severity: RuleSeverity.error,
        selector: ClassSelector(folder: 'lib/views'),
        predicate: NotPredicate(DependOnFolderPredicate('lib/models')),
      ),
    );
''';

const String _modelsNoViewModelDependency = r'''
// MVVM Architecture — generated by dartunit init --template mvvm
//
// Rule: Models must not depend on ViewModels.
// Models are pure data structures with no knowledge of the ViewModel layer.

import 'package:dartunit/dartunit.dart';

void main(List<String> args) => archTest(
      args,
      ArchitectureRule(
        description: 'Models must not depend on ViewModels',
        severity: RuleSeverity.error,
        selector: ClassSelector(folder: 'lib/models'),
        predicate: NotPredicate(DependOnFolderPredicate('lib/viewmodels')),
      ),
    );
''';

const String _servicesNoViewDependency = r'''
// MVVM Architecture — generated by dartunit init --template mvvm
//
// Rule: Services must not depend on views or viewmodels.
// Services are shared business logic and must remain UI-agnostic.

import 'package:dartunit/dartunit.dart';

void main(List<String> args) => archTest(
      args,
      ArchitectureRule(
        description: 'Services must not depend on views or viewmodels',
        severity: RuleSeverity.error,
        selector: ClassSelector(namePattern: r'.*Service$'),
        predicate: AndPredicate([
          NotPredicate(DependOnFolderPredicate('lib/views')),
          NotPredicate(DependOnFolderPredicate('lib/viewmodels')),
        ]),
      ),
    );
''';
