// teste_rule.dart
//
// Custom architecture rule generated by dartunit.
// Implement the build() method to define your rule logic.
//
// Documentation: .dartunit/README.md

import 'package:dartunit/dartunit.dart';

/// Teste
///
/// TODO: Add a detailed description of what this rule enforces and why.
///
/// Example violations that this rule catches:
/// - TODO: list example violations
///
/// Valid patterns that pass this rule:
/// - TODO: list valid patterns
class TesteRule implements CustomArchitectureRule {
  @override
  String get id => 'CUSTOM_TESTE';

  @override
  String get description => 'Teste';

  @override
  ArchitectureRule build() {
    // TODO: Configure the selector to choose which classes/files to check.
    //
    // Examples:
    //   ClassSelector(folder: 'lib/ui')           — all classes in lib/ui
    //   ClassSelector(namePattern: r'.*Bloc$')    — all Bloc classes
    //   ClassSelector(annotatedWith: 'injectable') — annotated classes
    //   FileSelector(folder: 'lib/domain')         — files in lib/domain
    //   LayerSelector(name: 'UI', folder: 'lib/ui')

    const selector = ClassSelector(
      folder: 'lib/', // TODO: restrict to the correct folder
    );

    // TODO: Configure the predicate that defines what the rule checks.
    //
    // Examples:
    //   DependOnFolderPredicate('lib/data')     — imports from lib/data
    //   NameEndsWithPredicate('Repository')     — name ends with suffix
    //   AnnotatedWithPredicate('injectable')    — has annotation
    //   MaxMethodsPredicate(10)                 — at most 10 methods
    //   NotPredicate(DependOnFolderPredicate('lib/data'))  — negation
    //   AndPredicate([pred1, pred2])            — both must pass
    //   OrPredicate([pred1, pred2])             — at least one must pass

    const predicate = MaxMethodsPredicate(10); // TODO: replace with actual predicate

    return ArchitectureRule(
      id: id,
      description: description,
      severity: RuleSeverity.error, // TODO: choose appropriate severity
      selector: selector,
      predicate: predicate,
    );
  }
}
