String generateMissingDartunit(String projectRoot) => '.dartunit/ not found in $projectRoot — run  dartunit init  first.';

String generateCreatedFile(String fileName) => 'Created  .dartunit/custom_rules/$fileName';

const String generateUpdatedConfig = 'Updated  .dartunit/dartunit.yaml';

List<String> generateNextSteps(String fileName) => [
      'Open    .dartunit/custom_rules/$fileName',
      'Implement the  build()  method with your rule logic.',
      'Run     dartunit analyze',
    ];

String ruleTemplate(String className, String ruleName, String ruleId) => '''
// Custom architecture rule generated by Dartunit.
// Implement the build() method to define your rule logic.
//
// Documentation: .dartunit/README.md

import 'package:dartunit/dartunit.dart';

/// ${_toDescription(ruleName)}
///
/// TODO: Add a detailed description of what this rule enforces and why.
///
/// Example violations that this rule catches:
/// - TODO: list example violations
///
/// Valid patterns that pass this rule:
/// - TODO: list valid patterns

class $className implements CustomArchitectureRule {
  @override
  String get id => '$ruleId';

  @override
  String get description => '${_toDescription(ruleName)}';

  @override
  ArchitectureRule build() {
    // TODO: Configure the selector to choose which classes/files to check.
    //
    // Examples:
    //   ClassSelector(folder: 'lib/ui')           — all classes in lib/ui
    //   ClassSelector(namePattern: r'.*Bloc\$')    — all Bloc classes
    //   ClassSelector(annotatedWith: 'injectable') — annotated classes
    //   FileSelector(folder: 'lib/domain')         — files in lib/domain
    //   LayerSelector(name: 'UI', folder: 'lib/ui')

    const selector = ClassSelector(
      folder: 'lib/', // TODO: restrict to the correct folder
    );

    // TODO: Configure the predicate that defines what the rule checks.
    //
    // Examples:
    //   DependOnFolderPredicate('lib/data')     — imports from lib/data
    //   NameEndsWithPredicate('Repository')     — name ends with suffix
    //   AnnotatedWithPredicate('injectable')    — has annotation
    //   MaxMethodsPredicate(10)                 — at most 10 methods
    //   NotPredicate(DependOnFolderPredicate('lib/data'))  — negation
    //   AndPredicate([pred1, pred2])            — both must pass
    //   OrPredicate([pred1, pred2])             — at least one must pass

    const predicate = MaxMethodsPredicate(10); // TODO: replace with actual predicate

    return ArchitectureRule(
      id: id,
      description: description,
      severity: RuleSeverity.error, // TODO: choose appropriate severity
      selector: selector,
      predicate: predicate,
    );
  }
}
''';

String yamlEntry(String ruleId, String fileName, String className) => '''

  # ── Custom rule: $className ───────────────────────────────────────────────
  - id: $ruleId
    type: custom
    implementation: $fileName
    description: "TODO: describe what $className enforces"
''';

String _toDescription(String ruleName) {
  return ruleName
      .split(RegExp(r'[_\-\s]+'))
      .map((w) => w.isEmpty ? '' : w[0].toUpperCase() + w.substring(1))
      .join(' ');
}
