import '../core/entities/violation.dart';
import '../core/extensions/string_extensions.dart';
import '../core/extensions/violation_list_extension.dart';
import 'html_css_theme.dart';

/// Generates a self-contained HTML report from a list of violations.
class HtmlReporter {

  String generate(
    List<Violation> violations, {
    required int rulesCount,
    required DateTime timestamp,
    required String projectRoot,
  }) {
    final sorted = violations.sortedBySeverity();
    final criticalCount = violations.criticalCount;
    final errorCount    = violations.errorCount;
    final warningCount  = violations.warningCount;
    final infoCount     = violations.infoCount;
    final ts = '${timestamp.year}-${_pad(timestamp.month)}-${_pad(timestamp.day)}'
        ' ${_pad(timestamp.hour)}:${_pad(timestamp.minute)}:${_pad(timestamp.second)}';
    final statusClass =
        violations.isEmpty ? 'pass' : (criticalCount > 0 || errorCount > 0 ? 'fail' : 'warn');
    final statusLabel =
        violations.isEmpty ? 'PASSED' : (errorCount > 0 || criticalCount > 0 ? 'FAILED' : 'WARNINGS');

    final buf = StringBuffer();
    buf.write(_docOpen(ts));
    buf.write(_header(_esc(projectRoot), ts, rulesCount, statusClass, statusLabel));
    buf.write(_summary(violations.length, criticalCount, errorCount, warningCount, infoCount));

    if (violations.isEmpty) {
      buf.write(_noViolations());
    } else {
      buf.write(_table(sorted, projectRoot));
    }

    buf.write(_docClose(ts));

    return buf.toString();
  }

  String _docOpen(String ts) => '''<!DOCTYPE html>
    <html lang="en">
    <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DartUnit — Architecture Report — $ts</title>
    <style>
    ${HtmlCssTheme.stylesheet}
    </style>
    </head>
    <body>
    <main>
    ''';

  String _header(String root, String ts, int rulesCount, String statusClass, String statusLabel) =>
      '''<header>
<div class="header-left">
  <h1>DartUnit</h1>
  <p class="subtitle">Architecture Analysis Report</p>
  <p class="meta">$root &bull; $ts &bull; $rulesCount rule${rulesCount == 1 ? '' : 's'}</p>
</div>
<div class="status $statusClass">$statusLabel</div>
</header>
''';

  String _summary(int total, int critical, int errors, int warnings, int info) => '''<section class="summary">
<div class="stat"><span class="num">$total</span><span class="lbl">total</span></div>
<div class="stat critical"><span class="num">$critical</span><span class="lbl">critical</span></div>
<div class="stat error"><span class="num">$errors</span><span class="lbl">errors</span></div>
<div class="stat warning"><span class="num">$warnings</span><span class="lbl">warnings</span></div>
<div class="stat info"><span class="num">$info</span><span class="lbl">info</span></div>
</section>
''';

  String _noViolations() => '''<section class="no-violations">
<p>&#10003; No architecture violations found.</p>
</section>
''';

  String _table(List<Violation> violations, String projectRoot) {
    final buf = StringBuffer();
    buf.writeln('<section class="violations">');
    buf.writeln('<table>');
    buf.writeln('<thead><tr>'
        '<th>Severity</th>'
        '<th>Rule</th>'
        '<th>File</th>'
        '<th>Line</th>'
        '<th>Message</th>'
        '</tr></thead>');
    buf.writeln('<tbody>');
    for (final v in violations) {
      final fileLink = _fileLink(projectRoot, v.filePath, v.line);
      buf.writeln('<tr class="${v.severity.name}">');
      buf.writeln('<td><span class="badge ${v.severity.name}">${v.severity.name}</span></td>');
      buf.writeln('<td class="description">${_esc(v.ruleDescription)}</td>');
      buf.writeln('<td class="file-path">$fileLink</td>');
      buf.writeln('<td class="line-num">${v.line?.toString() ?? '&mdash;'}</td>');
      buf.writeln('<td class="message">${_esc(v.message)}</td>');
      buf.writeln('</tr>');
    }
    buf.writeln('</tbody></table>');
    buf.writeln('</section>');
    return buf.toString();
  }

  /// Builds a clickable link that opens the file at [line] in VS Code.
  /// Falls back to a plain span if the path cannot be resolved.
  String _fileLink(String projectRoot, String filePath, int? line) {
    final escaped = _esc(filePath);
    if (filePath.isEmpty) return '<span>$escaped</span>';

    // Strip leading ./ and normalise separators to forward slashes.
    final relative = filePath.normalized.replaceFirst(RegExp(r'^\./'), '');
    final root = projectRoot.normalized;
    final absolute = '$root/$relative';
    final lineStr = line != null ? ':$line:1' : '';
    final href = 'vscode://file/$absolute$lineStr';

    return '<a class="file-link" href="${_esc(href)}" title="Open in VS Code">$escaped</a>';
  }

  String _docClose(String ts) => '''</main>
    <footer>Generated by dartunit &bull; $ts</footer>
    </body>
    </html>''';

  String _esc(String s) => s
      .replaceAll('&', '&amp;')
      .replaceAll('<', '&lt;')
      .replaceAll('>', '&gt;')
      .replaceAll('"', '&quot;');

  String _pad(int n) => n.toString().padLeft(2, '0');
}
